import io
import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_concor_rail_booking_pdf(container_id, route_info, sap_fo_id):
    """
    Generate CONCOR (Container Corporation of India) Multimodal Rail Booking PDF.
    Returns BytesIO object containing PDF bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        textColor=colors.HexColor('#0F172A'),
        alignment=1, # Center
        spaceAfter=12
    )

    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        textColor=colors.HexColor('#059669'),
        alignment=1,
        spaceAfter=15
    )

    body_bold = ParagraphStyle('BodyBold', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=10, textColor=colors.HexColor('#1E293B'))
    body_regular = ParagraphStyle('BodyRegular', parent=styles['Normal'], fontName='Helvetica', fontSize=10, textColor=colors.HexColor('#334155'))

    elements = []

    # Header Title
    elements.append(Paragraph("CONTAINER CORPORATION OF INDIA LTD. (CONCOR)", title_style))
    elements.append(Paragraph("SMARTEVAC WDFC MULTIMODAL RAIL WAYBILL & BOOKING ORDER", subtitle_style))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#059669'), spaceAfter=15))

    # General Information Table
    gen_data = [
        [Paragraph("<b>Document Reference:</b>", body_bold), Paragraph(f"CONCOR/WDFC/2026/{container_id}", body_regular),
         Paragraph("<b>Date of Issue:</b>", body_bold), Paragraph(datetime.datetime.now().strftime("%d-%b-%Y %H:%M HRS"), body_regular)],
        [Paragraph("<b>SAP Freight Order:</b>", body_bold), Paragraph(f"<b>{sap_fo_id}</b>", body_bold),
         Paragraph("<b>Transport Mode:</b>", body_bold), Paragraph(f"{route_info.get('mode', 'Rail Freight')}", body_regular)],
        [Paragraph("<b>Origin Terminal:</b>", body_bold), Paragraph("JNPA Port (Navi Mumbai)", body_regular),
         Paragraph("<b>Destination Rail ICD:</b>", body_bold), Paragraph("ICD Dadri (Delhi NCR Corridor)", body_regular)]
    ]

    t_gen = Table(gen_data, colWidths=[130, 150, 130, 130])
    t_gen.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    elements.append(t_gen)
    elements.append(Spacer(1, 15))

    # Cargo & Container Specific Details Header
    elements.append(Paragraph("<b>Container & Cargo Manifest Summary</b>", ParagraphStyle('SubHead', parent=styles['Heading2'], fontSize=12, textColor=colors.HexColor('#0F172A'))))
    elements.append(Spacer(1, 6))

    cargo_data = [
        [Paragraph("<b>Container ID</b>", body_bold), Paragraph("<b>Container Type</b>", body_bold), Paragraph("<b>Allocated Wagon No.</b>", body_bold), Paragraph("<b>Estimated Transit Time</b>", body_bold)],
        [Paragraph(f"<b>{container_id}</b>", body_regular), Paragraph("40ft High Cube TEU", body_regular), Paragraph(f"WDFC-BLC-{container_id[-4:]}", body_regular), Paragraph(f"{route_info.get('base_transit_hours', 24)} Hours", body_regular)]
    ]

    t_cargo = Table(cargo_data, colWidths=[130, 140, 140, 130])
    t_cargo.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#059669')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#059669')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#A7F3D0')),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    elements.append(t_cargo)
    elements.append(Spacer(1, 20))

    # Route Rationale & Stamp Section
    notes_p = Paragraph(
        "<b>Evacuation Authorization:</b> This electronic waybill authorizes immediate evacuation via the Dedicated Freight Corridor (WDFC) under JNPA SmartEvac Congestion Management Protocol. Automated gate dispatch generated by SAP TM Integration Suite.",
        body_regular
    )
    elements.append(notes_p)
    elements.append(Spacer(1, 30))

    # Signatures Table
    sig_data = [
        [Paragraph("<b>JNPA Port Operations</b>", body_bold), Paragraph("<b>CONCOR Rail Dispatch</b>", body_bold), Paragraph("<b>SAP TM Verification</b>", body_bold)],
        [Paragraph("[ELECTRONICALLY SIGNED]", body_regular), Paragraph("[STAMPED & VERIFIED]", body_regular), Paragraph("[SAP S/4HANA 200 OK]", body_regular)]
    ]
    t_sig = Table(sig_data, colWidths=[180, 180, 180])
    t_sig.setStyle(TableStyle([
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    elements.append(t_sig)

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()


def generate_customs_prefiling_pdf(container_id, cargo_desc, destination):
    """
    Generate Indian Customs (ICEGATE) Pre-filing & Gate Pass PDF.
    Returns BytesIO object containing PDF bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        textColor=colors.HexColor('#1E3A8A'),
        alignment=1,
        spaceAfter=12
    )

    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        textColor=colors.HexColor('#1D4ED8'),
        alignment=1,
        spaceAfter=15
    )

    body_bold = ParagraphStyle('BodyBold', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=10, textColor=colors.HexColor('#0F172A'))
    body_regular = ParagraphStyle('BodyRegular', parent=styles['Normal'], fontName='Helvetica', fontSize=10, textColor=colors.HexColor('#334155'))

    elements = []

    # Header Title
    elements.append(Paragraph("INDIAN CUSTOMS & CENTRAL EXCISE (ICEGATE)", title_style))
    elements.append(Paragraph("PORT EVACUATION PRE-CLEARANCE & GREEN CHANNEL GATE PASS", subtitle_style))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#1D4ED8'), spaceAfter=15))

    # General Details
    gen_data = [
        [Paragraph("<b>ICEGATE Reference:</b>", body_bold), Paragraph(f"ICE-JNPA-2026-{container_id}", body_regular),
         Paragraph("<b>Filing Status:</b>", body_bold), Paragraph("<font color='#059669'><b>GREEN CHANNEL APPROVED</b></font>", body_bold)],
        [Paragraph("<b>Container ID:</b>", body_bold), Paragraph(f"<b>{container_id}</b>", body_bold),
         Paragraph("<b>Port Gate Clearance:</b>", body_bold), Paragraph("JNPA Gate #4 (Priority Evacuation)", body_regular)],
        [Paragraph("<b>Cargo Description:</b>", body_bold), Paragraph(f"{cargo_desc}", body_regular),
         Paragraph("<b>Final Inland Destination:</b>", body_bold), Paragraph(f"{destination}", body_regular)]
    ]

    t_gen = Table(gen_data, colWidths=[130, 150, 130, 130])
    t_gen.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#EFF6FF')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#93C5FD')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#BFDBFE')),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    elements.append(t_gen)
    elements.append(Spacer(1, 20))

    # Customs Protocol Statement
    elements.append(Paragraph(
        "<b>Customs Pre-Filing Declaration:</b> The container listed above has been pre-cleared by Central Board of Indirect Taxes and Customs (CBIC) for high-speed evacuation from JNPA Port terminal under SmartEvac automated routing rules. RFID seal check pre-verified.",
        body_regular
    ))
    elements.append(Spacer(1, 25))

    # Signatures
    sig_data = [
        [Paragraph("<b>Customs Officer (JNPA Zone)</b>", body_bold), Paragraph("<b>JNPA Gate Security Controller</b>", body_bold)],
        [Paragraph("[DIGITALLY SIGNED - CBIC PKI]", body_regular), Paragraph("[VERIFIED AT SMART GATE]", body_regular)]
    ]
    t_sig = Table(sig_data, colWidths=[270, 270])
    t_sig.setStyle(TableStyle([
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    elements.append(t_sig)

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()
